### PR TITLE
feat: new dataset props

### PR DESCRIPTION
**Pull request by sdevalk**
This PR introduces 4 new properties for the `Dataset` type: 

1. mainEntityOfPages: the URIs where more info about a dataset can be found
2. dateCreated: the date at which the dataset was created
3. dateModified: the date at which the dataset was last modified
4. datePublished: the date at which the dataset was published

### CODE REVIEW

**Comment by barbarah** [comment]
Two questions: Should these properties also be added to the Cypress fixtures? I don't see these properties in the interface, are they needed?

**Review by barbarah — COMMENTED** [review]
Two questions: Should these properties also be added to the Cypress fixtures? I don't see these properties in the interface, are they needed?

**Comment by sdevalk** [comment]
Thanks!

> Two questions: Should these properties also be added to the Cypress fixtures?

Personally I'd wait for the UI/UX design to become a bit more clearer.

> I don't see these properties in the interface, are they needed?

Which interface do you mean? A TypeScript `interface`? Or the user interface?

**Comment by barbarah** [comment]
Sorry, I meant the user interface. I could not find these properties in the user interface.

Is the approach to fetch as much data as possible and see what the application needs later? Or do we want only to fetch what we need and only extend the fetcher if the application needs more properties?

**Comment by sdevalk** [comment]
> Sorry, I meant the user interface. I could not find these properties in the user interface.
> 
> Is the approach to fetch as much data as possible and see what the application needs later? Or do we want only to fetch what we need and only extend the fetcher if the application needs more properties?

Thanks - and good question. I see the dataset fetcher as a generic toolkit: it knows how to query the backends and which data they provide. The fetcher could even become a package on its own, not part of the Dataset Browser repository.

In the Dataset Browser we can cherry pick the data we need, based on e.g. UI and UX requirements.

**Review by barbarah — APPROVED** [review]

**Pull request merged**
